[build]
  base = "stock-yfinance-final"
  command = "pip install yfinance requests && echo done"
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"

[[scheduled_functions]]
  name = "daily-report"
  cron = "0 22 * * *"
